### ISSUE TITLE
Can't connect to room

### ISSUE THREAD

**Issue by webdevbrian** [atomjack/plugbotapi#32]
Just started getting "Sorry, I couldn't seem to connect." -- anyone else?

**Comment by ImGrumpy** [comment]
​I run bots in two separate rooms, they're both fine.​

**Comment by webdevbrian** [comment]
Crap ... just trying to figure out why I'm only having this issue then.

**Comment by atomjack** [comment]
Yeah, mine seems to be just fine as well.

**Comment by webdevbrian** [comment]
Crap!

**Comment by webdevbrian** [comment]
Hey Chris -- any cleaver ways of debugging this?

**Comment by atomjack** [comment]
Possibly. Here's what you can try, to generate some screenshots of the page that is causing problems. After the bot attempts to login, it waits for the next page to load, and tries up to 15 times to find a certain DOM element that will exist only after logged in and in a room. If, after 15 tries (2 seconds apart), it still can't find the element (and is thus not logged in), it shows the error you are getting, and stops.

Here's how you can generate some screenshots (you'll eventually get 15 of them):
Edit the index.js file that is part of the plugbotapi module, and go to line 134 (tries++;). Insert a new line after that, and add the following:

page.render('loggedin' + tries + '.png');
console.log("rendered image " + tries);

(if line 134 does not have just 'tries++;' on it, you may have a different (npm) version than what's in the repo, so here's the exact line in the repo: https://github.com/atomjack/plugbotapi/blob/master/index.js#L129)

Then, find the files it generates (loggedin1.png, loggedin2.png, etc), and view them (you can even upload to imgur and post here), and we can see what is going on. Look at all of the files and see if anything changes between one from the other.

**Comment by webdevbrian** [comment]
Totally forgot about just doing screenshots -- sorry Chris huge duh moment.

Thanks man -- i'll let you know what's up.

**Comment by webdevbrian** [comment]
![loggedin16](https://cloud.githubusercontent.com/assets/308749/8165901/31f6ad64-1362-11e5-8cf7-a3928b29bbad.png)

**Comment by webdevbrian** [comment]
literally all 16 images were the loading animation, and this isn't cropped -- the screenshot was taken @ 400x300px

**Comment by atomjack** [comment]
Look at line 204, maybe try changing the 15 to something higher, so it keeps checking longer? Although I doubt that will help. Also compare that screenshot with what you get when you try to login and go to a room in your browser - does it look like the login is successful, and it's just getting stuck on loading?

You might also add an eventhandler for page.onConsoleMessage (right after line 129, where it sets 'tries' to 0), to see if any errors are cropping up.

**Comment by webdevbrian** [comment]
Great ideas -- I'll report back in a few

**Comment by webdevbrian** [comment]
Looks like it's stuck on loading ... I wonder if plug bans IPs? Wouldn't make much sense...

But yeah, it's stuck on the loading of the page itself it appears -- onConsoleMessage wouldn't output anything

**Comment by webdevbrian** [comment]
Does this have anything to do with the fact that plug.dj is forcing traffic over HTTPS now? I was poking around the code and it looks like HTTP was designated and HTTPS was turned off ... is that accurate?

E.g: 
![screen shot 2015-06-15 at 14 16 23](https://cloud.githubusercontent.com/assets/308749/8166957/236a2f12-1369-11e5-87b6-c5f5e4a47c4f.png)

**Comment by atomjack** [comment]
Ah that could be it. I haven't really been paying attention, but has that change (to https) been just introduced in the last few days? My bot hasn't been restarted in 5 days. @ImGrumpy any idea how long your bots have been running for?

**Comment by webdevbrian** [comment]
Besides changing the page.open urls from http to https -- do you know what else I need to be changing? 

Just FYI -- My bot has been working perfectly thus far, this just happened over the weekend and I haven't touched my bot's code

**Comment by atomjack** [comment]
I'm not sure. I don't really have time to look at it right now. I'd suggest maybe just changing it on your end and see how it does. If you are successful, you might consider forking the repository and pulling your fork down, redoing the changes, and push them up and do a pull request. Then I can just merge them in (once I test on my end).

**Comment by webdevbrian** [comment]
Tried everything to get this thing to do a full size render, even after defining clipRect and viewport -- Chris, how have you been setting your screenshot sizes? I can't get anything but 400x300 shots : 
![screen shot 2015-06-15 at 2 36 16 pm](https://cloud.githubusercontent.com/assets/308749/8167376/e5be02f8-136b-11e5-9e2f-5f4c1df2064e.png)

**Comment by ImGrumpy** [comment]
One of mine has been up since last Wednesday, but the other one was
restarted a little under 5 hours ago.

**Comment by webdevbrian** [comment]
Christ - so I decided to wipe it clean and start fresh ...

    npm ERR! Error: ENOENT, lstat '/usr/local/share/npm/lib/node_modules/plugbotapi/node_modules/plug-dj-login/node_modules/request/node_modules/hawk/test/message.js'

Everything is a mess now.

**Comment by webdevbrian** [comment]
Fixed the above error -- wiped the directory clean, updated node, npm all that crap -- same issues as before.

Balls.

**Comment by ImGrumpy** [comment]
You had me curious, so I restarted my bot to see what happened and he came
back without issue.  Definitely not something Plug changed or that wouldn't
have worked.

**Comment by webdevbrian** [comment]
Thanks for the test @ImGrumpy

**Comment by webdevbrian** [comment]
@atomjack  -- got a render on line 258's page.open -- looks like the russion version of plug or something? Is this normal?

![screen](https://cloud.githubusercontent.com/assets/308749/8170154/b55739ac-137c-11e5-91ff-f0874a84f635.jpeg)

**Comment by atomjack** [comment]
Yeah. It defaults to some other language, Russian I guess, if you don't specify what language you want in the get request headers.

**Comment by webdevbrian** [comment]
Gotcha. Well here are all of the screenshots I get when trying to page.render after it 'logs in' -- I've tried everything to increase the viewport size from the default 400x300 and nothing is working, so I can't see what else is on the page (infuriating), and it just spins (which no one else is apparently getting).

http://i.imgur.com/qBuejZB.gif

**Comment by webdevbrian** [comment]
Question - is anyone else running this on OSX, or is everyone else running this on windows?

**Comment by nugget** [comment]
FreeBSD here.

**Comment by webdevbrian** [comment]
Found the god damn issue.

Dumping "cache" in the api wasn't working. I still can't set / change the rendered page viewport size (if anyone can get this working that'd be awesome because debugging is a huge pain in the ass @ 400x300).

You have to MANUALLY delete the cache localstorage files -- in OSX it was here for me :  
![screen shot 2015-06-17 at 14 04 36](https://cloud.githubusercontent.com/assets/308749/8214833/f5ca4438-14f9-11e5-90d2-f54dd5d08ccf.png)


After deleting the files the bot can log in.

I found this by aimlessly searching and stumbling on this link : http://qnalist.com/questions/5145851/empty-browser-cache

> ~/.qws/cache/Ofi Labs/PhantomJS
%AppData%/Local/Ofi Labs/PhantomJS/cache/http
but I suggest you to look on this pull request, implement it and build phantomjs. I made it and it works perfect, just add p.settings.clearMemoryCaches = [true|false] and that's it :)

This looks like the original posting for when they implemented (scraped obviously) -- of clearMemoryCaches. Trying to do that within the code it broke over and over, still couldn't figure that out, but finding out where this clearMemoryCaches was actually deleting the cache obviously fixed my problem.

What a total pain in the ass.
