### ISSUE TITLE
18 June Plug.dj update seems to have broken the API

### ISSUE THREAD

**Issue by nugget** [atomjack/plugbotapi#33]
Plug.dj went down this afternoon for a software update and since it has come back online neither of my bots are working.  They appear to connect but see no other users in the room.

It's like the data isn't making it through when an event fires.  For example, this code:

    bot.on('roomJoin', function(data) {
        util.log(util.inspect(data));

Yields:
    18 Jun 17:28:28 - undefined

so the roomJoin event is being processed, but data is empty/undefined .

**Comment by atomjack** [comment]
Yeah, I'm getting no users found as well. Kinda busy atm but will try to look into this later tonight, but if anyone wants to research it feel free.

**Comment by atomjack** [comment]
Looks like they rearranged the main page, changing a bunch of html elements around, which is why the bots are broken. Shouldn't take too long to fix.

**Comment by atomjack** [comment]
Ok, that turned out to be very easy. Can you guys try pulling down the latest from git and give it a try?

**Comment by nugget** [comment]
Confirmed fixed for me, thanks!
