### ISSUE TITLE
Can't add or remove bot from waitlist with API?

### ISSUE THREAD

**Issue by ImGrumpy** [atomjack/plugbotapi#35]
`bot.moderateAddDJ(config.botId, function(){});`
`bot.moderateRemoveDJ(config.botId, function(){});`

Neither seems to work.  Yes, I've confirmed that `config.botId` is the actual bot UID...  I've even replaced it with the actual UID number instead of a variable - it didn't help.  If I put another user's UID in there instead, such as my own, the commands work fine.

Any thoughts on this?

**Comment by ImGrumpy** [comment]
And yes, the bot has an activated playlist... and he's a manager, so he has access.

**Comment by ImGrumpy** [comment]
Any thoughts?  As a sign note, sometimes moderateRemoveDJ doesn't seem to work at all.  I've implemented it as a "remove" command in the bot - sometimes it works, sometimes it doesn't.  Not sure if that's related to this or not.

**Comment by ImGrumpy** [comment]
Unfortunately this seems abandoned, so I was forced to switch APIs for a solve.

**Comment by webdevbrian** [comment]
moderateAddDJ for me works ... ?

**Comment by ImGrumpy** [comment]
@webdevbrian in general it was working, but I could NOT get it to add the bot no matter what I tried.
